# Generated by Django 4.2.2 on 2023-06-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_category_name_en_category_name_ru_category_name_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='body2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='body3',
        ),
        migrations.RemoveField(
            model_name='news',
            name='body4',
        ),
        migrations.RemoveField(
            model_name='news',
            name='body5',
        ),
    ]
