# Generated by Django 4.2.2 on 2023-07-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_rename_news_comment_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time']},
        ),
    ]
